Repository Andx667/advanced_slingloading_redux, pull requests merged in 2025-09, with the labels that each got.

#12 general - Add hemtt launch mission
  .hemtt/launch.toml
  .hemtt/missions/VR.VR/mission.sqm
Labels: pr/feature

#13 resolve hemtt warning
  addons/core/initKeybinds.inc.sqf
  addons/core/initSettings.inc.sqf
  addons/core/stringtable.xml
  addons/main/stringtable.xml
Labels: ignore-changelog

#15 Core - Add Custom Helper Object to replace "Land_Can_V2_F"
  addons/core/CfgVehicles.hpp
  addons/core/config.cpp
  addons/core/data/logo_aslr_ca.paa
  addons/core/data/logo_aslr_icon_only.paa
  addons/main/stringtable.xml
  img/logo_aslr_icon_only.paa
  img/logo_aslr_icon_only.png
Labels: pr/feature

#16 Tools - Improved launch.toml + mission.sqm
  .hemtt/launch.toml
  .hemtt/missions/VR.VR/mission.sqm
Labels: tools

#18 tools - Update Release toolchain
  .hemtt/hooks/post_build/post_build.rhai
  .hemtt/hooks/post_release/01_move_readme.rhai
  .hemtt/hooks/post_release/post_release.rhai
  .hemtt/hooks/pre_build/01_set_version.rhai
  .hemtt/hooks/pre_release/pre_release.rhai
  .hemtt/scripts/update_modcpp_version.rhai
Labels: tools

#19 Versioning streamline
  .github/workflows/release.yml
  .hemtt/hooks/post_build/post_build.rhai
  .hemtt/hooks/post_release/post_release.rhai
  .hemtt/hooks/pre_build/pre_build.rhai
  .hemtt/hooks/pre_release/pre_release.rhai
  .hemtt/scripts/bump_build.rhai
  .hemtt/scripts/bump_minor.rhai
  .hemtt/scripts/bump_patch.rhai
  .hemtt/scripts/update_version_modcpp.rhai
  .hemtt/scripts/update_version_readme.rhai
  meta.cpp
  mod.cpp
Labels: tools

#20 fix name of branch
  .github/workflows/release-drafter.yml
Labels: tools

#24 tools - Fix release drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: tools

#27 tools - Add a discord notification on release
  .github/workflows/discord-notice.yml
Labels: tools

#33 Tools - Polish Readme
  README.md
Labels: tools

#36 general - Improve readme
  README.md
Labels: ignore-changelog
