Repository Andx667/advanced_slingloading_redux, pull requests merged in 2025-10, with the labels that each got.

#42 core - Add config height offset
  addons/core/ASLR_Hooks_HeightOffset.hpp
  addons/core/config.cpp
Labels: pr/feature

#43 core - Add config for hooks
  addons/core/ASLR_Hooks.hpp
  addons/core/config.cpp
Labels: pr/feature

#45 core - Add refined `getSlingloadPoints` System
  .hemtt/missions/VR.VR/mission.sqm
  addons/core/ASLR_Hooks.hpp
  addons/core/ASLR_Hooks_HeightOffset.hpp
  addons/core/XEH_PREP.hpp
  addons/core/functions/fnc_deployRopes.sqf
  addons/core/functions/fnc_deployRopesAction.sqf
  addons/core/functions/fnc_deployRopesIndex.sqf
  addons/core/functions/fnc_getHooksData.sqf
  addons/core/functions/fnc_getHooksDefault.sqf
  addons/core/functions/fnc_getHooksDefaultHeightOffset.sqf
  addons/core/functions/fnc_getHooksFromConfig.sqf
  addons/core/functions/fnc_initAirframe.sqf
  addons/main/script_version.hpp
Labels: pr/feature

#52 core - Add Setting to ignore Lift Capability & Allow locked Vehicles
  .hemtt/missions/VR.VR/cba_settings.sqf
  .hemtt/missions/VR.VR/description.ext
  .hemtt/missions/VR.VR/mission.sqm
  addons/core/XEH_PREP.hpp
  addons/core/functions/fnc_attachRopes.sqf
  addons/core/functions/fnc_attachRopesAction.sqf
  addons/core/functions/fnc_deployRopesAction.sqf
  addons/core/functions/fnc_getRopeLiftCapabiliy.sqf
  addons/core/functions/fnc_pickupRopesAction.sqf
  addons/core/functions/fnc_ropeAdjustMass.sqf
  addons/core/initSettings.inc.sqf
  addons/core/stringtable.xml
  addons/main/script_version.hpp
Labels: pr/feature

#61 Core - Fix missing Stringtable entry `str_aslr_core_cannot_pickup_locked_vehicle`
  addons/core/stringtable.xml
Labels: ignore-changelog

#63 Core - Fix infinite Shorten of Ropes
  addons/core/functions/fnc_canShortenRopes.sqf
  addons/core/functions/fnc_shortenRopesIndexAction.sqf
Labels: pr/bug-fix
